plugins {
    id 'architectury-plugin'
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

loom {
    neoForge {
    }
}

loom {
    accessWidenerPath = file(project(":arclight-common").file('src/main/resources/arclight.classtweaker'))
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge libs.neoforge

    implementation libs.izzel.tools
    implementation libs.arclight.api
    //implementation libs.mixin.tools

    common(libs.bundles.spigot.shade) { transitive = false }
    shadowCommon(libs.bundles.spigot.shade) { transitive = false }
    common rootProject.ext.generatedSpigot
    shadowCommon rootProject.ext.generatedSpigot

    // XXX: for compiling (arclight-api): NeoForgeArclightServer#registerForgeEvent
    compileOnly("net.minecraftforge:eventbus:4.0.0") { transitive = false }

    implementation(project(':i18n-config')) { transitive = false }

    common(project(path: ':arclight-common')) { transitive = false }
    shadowCommon(project(path: ':arclight-common', configuration: 'transformProductionNeoForge')) { transitive = false }
}

processResources {
    def ver = "${project.version}+$gitHash"
    inputs.property 'version', ver

    filesMatching('META-INF/neoforge.mods.toml') {
        expand 'version': ver
    }
}

jar {
    archiveClassifier = "raw"
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    dependsOn jar
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    zip64 = true
    from rootProject.file("LICENSE")
}

assemble.dependsOn shadowJar

/*
remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    atAccessWideners.add(loom.accessWidenerPath.get().asFile.getName())
}
*/

tasks.register('srgJar', Jar) {
    from(tasks.jar.outputs.files.collect { it.isDirectory() ? it : zipTree(it) }) {
        include 'io/izzel/**'
        exclude 'io/izzel/arclight/common/mixin/**'
    }
    archiveClassifier.set('srg')
    dependsOn jar
}

sourcesJar {
    def commonSources = rootProject.ext.commonProject.sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}
